(in-package #:vcs-kit)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (export '(
   ;; Observation records.
   git-status
   git-diff
   git-diff-stat
   git-diff-name-status
   git-diff-numstat
   git-show
   git-log
   git-reflog
   git-rev-list
   git-rev-parse
   git-rev-parse-value
   git-for-each-ref
   git-show-ref
   git-symbolic-ref
   git-merge-base
   git-cat-file
   git-ls-tree
   git-ls-files
   git-check-ignore
   git-check-attr
   git-check-ref-format
   git-diff-check
   git-diff-files
   git-diff-index
   git-diff-tree
   git-count-objects
   git-describe
   git-blame
   git-annotate
   git-grep
   git-shortlog
   git-show-branch
   git-whatchanged
   git-cherry
   git-check-mailmap
   git-column
   git-diff-pairs
   git-format-rev
   git-get-tar-commit-id
   git-interpret-trailers
   git-last-modified
   git-ls-remote
   git-name-rev
   git-patch-id
   git-range-diff
   git-show-index
   git-var

   ;; Working-tree and history mutation.
   git-add
   git-stage
   git-commit
   git-branch
   git-switch
   git-checkout
   git-restore
   git-reset
   git-rm
   git-mv
   git-clean
   git-tag
   git-update-ref
   git-merge
   git-rebase
   git-cherry-pick
   git-revert
   git-stash
   git-sparse-checkout
   git-rerere

   ;; Auxiliary Git, collaboration, and diagnostic commands.
   git-backfill
   git-bugreport
   git-citool
   git-diagnose
   git-difftool
   git-filter-branch
   git-for-each-repo
   git-help
   git-instaweb
   git-mergetool
   git-pack-refs
   git-refs
   git-replay
   git-repo
   git-request-pull

   ;; Remote, worktree, submodule, and maintenance commands.
   git-remote
   git-fetch
   git-pull
   git-push
   git-worktree
   git-submodule
   git-notes
   git-bisect
   git-archive
   git-bundle
   git-format-patch
   git-am
   git-apply
   git-fast-export
   git-fast-import
   git-archimport
   git-cvsexportcommit
   git-cvsimport
   git-cvsserver
   git-imap-send
   git-p4
   git-quiltimport
   git-send-email
   git-svn
   git-maintenance
   git-gc
   git-prune
   git-prune-packed
   git-repack
   git-fsck

   ;; Plumbing and object/index commands.
   git-commit-tree
   git-config
   git-credential
   git-fmt-merge-msg
   git-fsck-objects
   git-hash-object
   git-hook
   git-index-pack
   git-init-db
   git-mailinfo
   git-mailsplit
   git-merge-file
   git-merge-index
   git-merge-tree
   git-mktag
   git-mktree
   git-pack-objects
   git-pack-redundant
   git-read-tree
   git-receive-pack
   git-replace
   git-send-pack
   git-stripspace
   git-unpack-file
   git-unpack-objects
   git-update-index
   git-update-server-info
   git-upload-archive
   git-upload-pack
   git-verify-commit
   git-verify-pack
   git-verify-tag
   git-write-tree
   git-checkout-index
   git-commit-graph
   git-multi-pack-index

    )))
