(in-package #:vcs-kit)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (export '(
   ;; Repository handles.
   repository
   repository-p
   make-repository
   repository-directory
   repository-git-directory
   repository-common-directory
   repository-bare-p
   repository-executable
   repository-default-timeout
   repository-environment
   open-repository

   ;; Structured operation logging.
   *vcs-logger*

   ;; Direct process-kit results.
   process-result
   process-result-program
   process-result-arguments
   process-result-pid
   process-result-status
   process-result-duration-seconds
   process-result-exit-code
   process-result-stdout
   process-result-stderr
   process-result-timed-out-p
   process-result-cancelled-p
   process-result-signal
   process-result-stdout-truncated-p
   process-result-stderr-truncated-p
   process-success-p

   ;; Shared process cancellation.
   vcs-cancellation-token
   make-vcs-cancellation-token
   cancel-vcs
   vcs-cancellation-requested-p

   ;; Conditions.
   vcs-error
   git-error
   git-error-repository
   git-error-command
   git-error-arguments
   git-error-result
   git-error-cause
   git-error-directory
   git-exit-error
   git-exit-error-exit-code
   git-timeout-error
   git-cancelled-error
   git-launch-error
   git-io-error
   git-io-error-stream
   git-parse-error
   git-parse-error-format-name
   git-parse-error-record
   git-parse-error-position

   ;; GHQ conditions.
   ghq-error
   ghq-error-command
   ghq-error-arguments
   ghq-error-result
   ghq-error-cause
   ghq-error-directory
   ghq-exit-error
   ghq-exit-error-exit-code
   ghq-timeout-error
   ghq-cancelled-error
   ghq-launch-error
   ghq-io-error
   ghq-io-error-stream

   ;; Low-level execution, asynchronous tasks, and synchronous CPS entry
   ;; points.
   run-git
   run-git-async
   run-git/checked
   run-git/k
   git-version
   git-version-async
   run-ghq
   run-ghq-async
   run-ghq/checked
   run-ghq/k
   ghq-version
   ghq-version-async
   parse-ghq-lines
   await-vcs-task
   cancel-vcs-task
   vcs-task-state
   vcs-task-result
   vcs-task-condition
   vcs-task-events
   next-vcs-event
   vcs-task-callback-errors
   vcs-task-dropped-event-count

   ;; Structured status and diff records.
   status-snapshot
   status-snapshot-p
   status-snapshot-branch-head
   status-snapshot-branch-upstream
   status-snapshot-ahead
   status-snapshot-behind
   status-snapshot-stash-count
   vcs-argument-error
   vcs-argument-error-argument
   vcs-argument-error-position
   vcs-argument-error-reason
   status-snapshot-entries
   status-entry
   status-entry-p
   status-entry-kind
   status-entry-index-status
   status-entry-worktree-status
   status-entry-submodule
   status-entry-head-mode
   status-entry-index-mode
   status-entry-worktree-mode
   status-entry-conflict-mode-1
   status-entry-conflict-mode-2
   status-entry-conflict-mode-3
   status-entry-head-object
   status-entry-index-object
   status-entry-conflict-object-1
   status-entry-conflict-object-2
   status-entry-conflict-object-3
   status-entry-score
   status-entry-path
   status-entry-original-path
   name-status-entry
   name-status-entry-p
   name-status-entry-status
   name-status-entry-path
   name-status-entry-original-path
   numstat-entry
   numstat-entry-p
   numstat-entry-additions
   numstat-entry-deletions
   numstat-entry-path
   numstat-entry-original-path
   numstat-entry-binary-p
   vcs-status-snapshot
   vcs-status-snapshot-p
   vcs-status-snapshot-branch-head
   vcs-status-snapshot-branch-upstream
   vcs-status-snapshot-ahead
   vcs-status-snapshot-behind
   vcs-status-snapshot-stash-count
   vcs-status-snapshot-entries
   vcs-status-entry
   vcs-status-entry-p
   vcs-status-entry-kind
   vcs-status-entry-index-status
   vcs-status-entry-worktree-status
   vcs-status-entry-submodule
   vcs-status-entry-path
   vcs-status-entry-original-path
   vcs-status-entry-conflict-object-1
   vcs-status-entry-conflict-object-2
   vcs-status-entry-conflict-object-3
   vcs-remote
   vcs-remote-p
   vcs-remote-name
   vcs-remote-fetch-url
   vcs-remote-push-url
   vcs-remote-fetch-refspecs
   vcs-remote-push-refspecs
   vcs-branch
   vcs-branch-p
   vcs-branch-name
   vcs-branch-current-p
   vcs-branch-upstream
   vcs-branch-ahead
   vcs-branch-behind
   vcs-tag
   vcs-tag-p
   vcs-tag-name
   vcs-tag-target
   vcs-tag-annotated-p
   vcs-tag-message
   vcs-tag-tagger
   vcs-tag-signature-status
   vcs-commit
   vcs-commit-p
   vcs-commit-id
   vcs-commit-parents
   vcs-commit-tree
   vcs-commit-author
   vcs-commit-committer
   vcs-commit-authored-at
   vcs-commit-committed-at
   vcs-commit-message
   vcs-commit-encoding
   vcs-diff-entry
   vcs-diff-entry-p
   vcs-diff-entry-status
   vcs-diff-entry-path
   vcs-diff-entry-original-path
   vcs-diff-entry-additions
   vcs-diff-entry-deletions
   vcs-diff-entry-binary-p
   vcs-conflict
   vcs-conflict-p
   vcs-conflict-path
   vcs-conflict-base
   vcs-conflict-ours
   vcs-conflict-theirs
   vcs-stash-entry
   vcs-stash-entry-p
   vcs-stash-entry-reference
   vcs-stash-entry-message
   vcs-stash-entry-date
   vcs-worktree
   vcs-worktree-p
   vcs-worktree-path
   vcs-worktree-head
   vcs-worktree-branch
   vcs-worktree-bare-p
   vcs-worktree-locked-p
   vcs-worktree-prunable-p
   vcs-submodule
   vcs-submodule-p
   vcs-submodule-path
   vcs-submodule-name
   vcs-submodule-url
   vcs-submodule-head
   vcs-submodule-index
   vcs-submodule-worktree-status
   split-nul-records
   parse-status
   parse-name-status
   parse-numstat

   ;; Repository creation and discovery.
   git-init
   git-clone

    )))
