(in-package #:vcs-kit)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (export '(
   ;; Backend-neutral VCS API.
   vcs-backend
   vcs-backend-p
   make-vcs-backend
   vcs-backend-name
   vcs-backend-executable
   vcs-backend-aliases
   vcs-backend-capabilities
   vcs-backend-commands
   vcs-backend-operation-kinds
   vcs-backend-structured-operations
   vcs-backend-markers
   vcs-operation-info
   vcs-operation-info-p
   vcs-operation-info-operation
   vcs-operation-info-command
   vcs-operation-info-mapping-kind
   vcs-repository
   vcs-repository-p
   make-vcs-repository
   vcs-repository-directory
   vcs-repository-backend
   vcs-repository-executable
   vcs-repository-default-timeout
   vcs-repository-environment
   available-vcs-backends
   find-vcs-backend
   register-vcs-backend
   unregister-vcs-backend
   vcs-backend-supports-operation-p
   vcs-supported-operations
   vcs-backend-supports-structured-operation-p
   vcs-structured-operations
   vcs-operation-command
   vcs-operation-kind
   detect-vcs-backend
   open-vcs-repository
   discover-vcs-repository
   vcs-command-error
   vcs-command-error-repository
   vcs-command-error-command
   vcs-command-error-arguments
   vcs-command-error-result
   vcs-command-error-cause
   vcs-command-error-directory
   vcs-command-exit-error
   vcs-command-exit-error-exit-code
   vcs-command-timeout-error
   vcs-command-cancelled-error
   vcs-command-launch-error
   vcs-command-io-error
   vcs-command-io-error-stream
   vcs-backend-error
   vcs-backend-error-backend
   vcs-unknown-backend-error
   vcs-unknown-backend-error-designator
   vcs-unknown-backend-error-known-backends
   vcs-backend-registration-error
   vcs-backend-registration-error-designator
   vcs-backend-registration-error-conflicting-backend
   vcs-backend-detection-error
   vcs-backend-detection-error-directory
   vcs-unsupported-operation-error
   vcs-unsupported-operation-error-repository
   vcs-unsupported-operation-error-operation
   vcs-unsupported-operation-error-capabilities
   run-vcs
   run-vcs-async
   run-vcs/checked
   run-vcs/k
   vcs-version
   vcs-version-async
   run-vcs-operation
   run-vcs-operation-async
   run-vcs-operation/k
   vcs-status
   vcs-diff
   vcs-log
   vcs-show
   vcs-cat
   vcs-add
   vcs-remove
   vcs-move
   vcs-commit
   vcs-branch
   vcs-switch
   vcs-checkout
   vcs-tag
   vcs-fetch
   vcs-pull
   vcs-push
   vcs-merge
   vcs-rebase
   vcs-reset
   vcs-revert
   vcs-stash
   vcs-remote
   vcs-update
   vcs-sync
   vcs-archive
   vcs-annotate
   vcs-blame
   vcs-resolve
   vcs-clean
   vcs-lock
   vcs-unlock
   vcs-config
   vcs-help
   vcs-worktree
   vcs-submodule
   vcs-bundle
   vcs-maintenance
   vcs-verify
   vcs-init
   vcs-clone

   ;; Backend-neutral structured observations.
   vcs-status-structured
   vcs-diff-entries
   vcs-list-remotes
   vcs-list-branches
   vcs-list-tags
   vcs-list-commits
   vcs-list-stashes
   vcs-list-conflicts
   vcs-list-worktrees
   vcs-list-submodules

    )))
